# Generated by Django 3.2.3 on 2021-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=50)),
                ('qty', models.BigIntegerField()),
                ('rate', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=50)),
                ('byerGSTN', models.CharField(max_length=50)),
                ('invoice_no', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('total', models.FloatField()),
                ('Gtotal', models.FloatField()),
                ('product', models.ManyToManyField(to='bill.Product')),
            ],
        ),
    ]
