# Generated by Django 3.2.3 on 2021-11-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20211128_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cgst',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sgst',
            field=models.FloatField(null=True),
        ),
    ]
